default: &DEFAULT
  num_data_workers: 1
  # model
  model: 'fno'
  depth: 5
  in_dim: 2
  out_dim: 1
  dropout: 0
  # data/domain
  Lx: !!float 1.0
  Ly: !!float 1.0
  nx: 256
  ny: 256
  # optimization
  loss_style: 'mean'
  loss_func: 'mse'
  optimizer: 'adam'
  scheduler: 'none'
  lr: !!float 1.0
  max_epochs: 500
  max_cosine_lr_epochs: 500
  batch_size: 25
  # misc
  log_to_screen: !!bool True
  save_checkpoint: !!bool False
  seed: 0
  plot_figs: !!bool False
  pack_data: !!bool False
  # Weights & Biases
  # Weights & Biases
  entity: 'ucl-neural-operator'
  project: 'foundational-no'
  distill: !!bool False
  subsample: 1

advdiff: &advdiff
  <<: *DEFAULT
  batch_size: 32
  valid_batch_size: 32
  nx: 128
  ny: 128
  log_to_wandb: !!bool True
  save_checkpoint: !!bool True
  max_epochs: 500
  scheduler: 'cosine'
  plot_figs: !!bool True
  loss_style: 'sum'

  model: 'fno'
  layers: [64, 64, 64, 64, 64]
  modes1: [65, 65, 65, 65]
  modes2: [65, 65, 65, 65]
  fc_dim: 128

  in_dim: 6
  out_dim: 1
  mode_cut: 32
  embed_cut: 128
  fc_cut: 2

  optimizer: 'adam'

  lr: 0.0005
  pack_data: !!bool False

fno-foundational: &fno-foundational
  <<: *advdiff
  train_path:   '/mnt/data/multipde/_train_mixed_32k.h5'
  val_path:     '/mnt/data/multipde/_val_mixed_4k.h5'
  test_path:    'neuralop/data/datasets/data/test_mixed.h5'
  scales_path:  'neuralop/data/datasets/data/scale_mixed.npy'
  batch_size: 32
  valid_batch_size: 32
  log_to_wandb: !!bool True
  mode_cut: 32
  embed_cut: 128
  fc_cut: 2